openapi: 3.0.0
info:
    title: Super Umbrella
    description: Super Umbrella
    version: 1.0.0
servers:
    -   url: 'https://test.local'
        description: 'Local Super Umbrella Server'
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
paths:
    /:
        get:
            security:
                - bearerAuth: []
            description: 'Test if server is working'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: OK